-- Refonte : exercices au poids du corps (PDC) + lest, unilatéralité, profil + suivi du poids.
-- À exécuter dans l'éditeur SQL Supabase (ou via `supabase db push`).

-- M1 — flags exo (PDC + unilatéral). DEFAULT false ⇒ rétrocompat des lignes existantes.
ALTER TABLE public.exos
  ADD COLUMN IF NOT EXISTS is_bodyweight boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_unilateral boolean NOT NULL DEFAULT false;

-- M2 — profil statique (1 ligne par utilisateur).
CREATE TABLE IF NOT EXISTS public.profiles (
  user_id    text PRIMARY KEY DEFAULT (auth.jwt() ->> 'sub'),
  sexe       text CHECK (sexe IN ('H','F','A')),   -- A = autre / non précisé
  taille_cm  smallint CHECK (taille_cm BETWEEN 80 AND 260),
  birth_date date,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS profiles_select_own ON public.profiles;
DROP POLICY IF EXISTS profiles_insert_own ON public.profiles;
DROP POLICY IF EXISTS profiles_update_own ON public.profiles;
CREATE POLICY profiles_select_own ON public.profiles
  FOR SELECT USING (user_id = (auth.jwt() ->> 'sub'));
CREATE POLICY profiles_insert_own ON public.profiles
  FOR INSERT WITH CHECK (user_id = (auth.jwt() ->> 'sub'));
CREATE POLICY profiles_update_own ON public.profiles
  FOR UPDATE USING (user_id = (auth.jwt() ->> 'sub'))
             WITH CHECK (user_id = (auth.jwt() ->> 'sub'));

-- M3 — historique du poids de corps (N lignes datées ⇒ courbe d'évolution).
CREATE TABLE IF NOT EXISTS public.bodyweights (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    text NOT NULL DEFAULT (auth.jwt() ->> 'sub'),
  date       date NOT NULL DEFAULT current_date,
  poids_kg   numeric NOT NULL CHECK (poids_kg > 0 AND poids_kg < 500),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, date)   -- une mesure par jour : re-saisir le même jour fait un upsert
);

ALTER TABLE public.bodyweights ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS bodyweights_select_own ON public.bodyweights;
DROP POLICY IF EXISTS bodyweights_insert_own ON public.bodyweights;
DROP POLICY IF EXISTS bodyweights_update_own ON public.bodyweights;
DROP POLICY IF EXISTS bodyweights_delete_own ON public.bodyweights;
CREATE POLICY bodyweights_select_own ON public.bodyweights
  FOR SELECT USING (user_id = (auth.jwt() ->> 'sub'));
CREATE POLICY bodyweights_insert_own ON public.bodyweights
  FOR INSERT WITH CHECK (user_id = (auth.jwt() ->> 'sub'));
CREATE POLICY bodyweights_update_own ON public.bodyweights
  FOR UPDATE USING (user_id = (auth.jwt() ->> 'sub'))
             WITH CHECK (user_id = (auth.jwt() ->> 'sub'));
CREATE POLICY bodyweights_delete_own ON public.bodyweights
  FOR DELETE USING (user_id = (auth.jwt() ->> 'sub'));
