-- Planification de séance + abonnements Web Push.
-- À exécuter dans l'éditeur SQL Supabase (convention du projet : migrations manuelles).

-- Séances planifiées : 1 type par jour et par utilisateur.
CREATE TABLE IF NOT EXISTS public.planned_sessions (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    text NOT NULL DEFAULT (auth.jwt() ->> 'sub'),
  date       date NOT NULL,
  type       text NOT NULL CHECK (type IN ('push','pull','legs','full','upper','core','athletics')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, date)
);

ALTER TABLE public.planned_sessions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS planned_select_own ON public.planned_sessions;
DROP POLICY IF EXISTS planned_insert_own ON public.planned_sessions;
DROP POLICY IF EXISTS planned_update_own ON public.planned_sessions;
DROP POLICY IF EXISTS planned_delete_own ON public.planned_sessions;
CREATE POLICY planned_select_own ON public.planned_sessions
  FOR SELECT USING (user_id = (auth.jwt() ->> 'sub'));
CREATE POLICY planned_insert_own ON public.planned_sessions
  FOR INSERT WITH CHECK (user_id = (auth.jwt() ->> 'sub'));
CREATE POLICY planned_update_own ON public.planned_sessions
  FOR UPDATE USING (user_id = (auth.jwt() ->> 'sub'))
             WITH CHECK (user_id = (auth.jwt() ->> 'sub'));
CREATE POLICY planned_delete_own ON public.planned_sessions
  FOR DELETE USING (user_id = (auth.jwt() ->> 'sub'));

-- Abonnements Web Push (1 par appareil/navigateur).
CREATE TABLE IF NOT EXISTS public.push_subscriptions (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    text NOT NULL DEFAULT (auth.jwt() ->> 'sub'),
  endpoint   text NOT NULL UNIQUE,
  p256dh     text NOT NULL,
  auth       text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS push_select_own ON public.push_subscriptions;
DROP POLICY IF EXISTS push_insert_own ON public.push_subscriptions;
DROP POLICY IF EXISTS push_delete_own ON public.push_subscriptions;
CREATE POLICY push_select_own ON public.push_subscriptions
  FOR SELECT USING (user_id = (auth.jwt() ->> 'sub'));
CREATE POLICY push_insert_own ON public.push_subscriptions
  FOR INSERT WITH CHECK (user_id = (auth.jwt() ->> 'sub'));
CREATE POLICY push_delete_own ON public.push_subscriptions
  FOR DELETE USING (user_id = (auth.jwt() ->> 'sub'));
